import { chromium } from 'playwright';
const EXEC = '/opt/pw-browsers/chromium-1194/chrome-linux/chrome';
const b = await chromium.launch({ executablePath: EXEC, args: ['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader'] });
const ctx = await b.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 1, hasTouch: true, isMobile: true });
const page = await ctx.newPage();
const logs = [];
page.on('console', m => { if (m.type()!=='log') logs.push(`[${m.type()}] ${m.text()}`); });
page.on('pageerror', e => logs.push(`[pageerror] ${e.message}`));
await page.goto('http://127.0.0.1:4173/', { waitUntil: 'load' });
const frames = (n) => page.evaluate((k)=>new Promise(r=>{let i=0;const t=()=>(++i>=k?r(null):requestAnimationFrame(t));requestAnimationFrame(t);}), n);
const st = () => page.evaluate(() => window.__game.debugState());
const until = async (pred, label, max=1600) => { for(let i=0;i<max;i++){ const s = await st(); if(pred(s)) return s; await frames(1);} throw new Error('timeout '+label+' '+JSON.stringify(await st())); };
await frames(4);
await page.mouse.click(195, 340);
for (let round = 1; round <= 3; round++) {
  await until(s=>s.phase==='wait','wait');
  await until(s=>s.hooked>=1,'bite1');
  await frames(60);
  await page.evaluate(() => window.__game.forcePress(true));
  const m = await until(s=>s.phase==='mobile','mobile');
  await page.evaluate(() => window.__game.forcePress(false));
  await frames(10);
  await page.screenshot({ path: `shots/cyc-${round}-mobile.png` });
  console.log('round', round, 'fish', m.fish, 'hooked', m.hooked);
  await page.evaluate(() => window.__game.forceTap());
  await frames(20);
  await page.screenshot({ path: `shots/cyc-${round}-unhook.png` });
  const t = await until(s=>s.phase==='tank','tank');
  await frames(24);
  await page.screenshot({ path: `shots/cyc-${round}-tank.png` });
  console.log('  tank at round', t.round);
  await page.evaluate(() => window.__game.forceTap());
  const d = await until(s=>s.phase==='deploy'||s.phase==='wait','redeploy');
  await frames(8);
  await page.screenshot({ path: `shots/cyc-${round}-redeploy.png` });
  console.log('  redeployed round', d.round, d.phase);
}
console.log(logs.join('\n')||'(clean console)');
await b.close();
