import { chromium } from 'playwright';
const EXEC = '/opt/pw-browsers/chromium-1194/chrome-linux/chrome';
const W = Number(process.env.W ?? 390), H = Number(process.env.H ?? 844), DPR = Number(process.env.DPR ?? 2);
const b = await chromium.launch({ executablePath: EXEC, args: ['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--ignore-gpu-blocklist'] });
const ctx = await b.newContext({ viewport: { width: W, height: H }, deviceScaleFactor: DPR, hasTouch: true, isMobile: true });
const page = await ctx.newPage();
const logs = [];
page.on('console', m => { if (m.type()!=='log') logs.push(`[${m.type()}] ${m.text()}`); });
page.on('pageerror', e => logs.push(`[pageerror] ${e.message}`));
await page.goto('http://127.0.0.1:4173/', { waitUntil: 'load' });
const frames = (n) => page.evaluate((k)=>new Promise(r=>{let i=0;const t=()=>(++i>=k?r(null):requestAnimationFrame(t));requestAnimationFrame(t);}), n);
const st = () => page.evaluate(() => window.__game.debugState());
const until = async (pred, label, max=900) => { for(let i=0;i<max;i++){ const s = await st(); if(pred(s)) return s; await frames(1);} throw new Error('timeout '+label+' '+JSON.stringify(await st())); };
await frames(4);
await page.mouse.click(W/2, H*0.4);
await until(s=>s.hooked>=1,'bite');
await frames(4);
await page.screenshot({ path: 'shots/peek-bite.png' });
console.log('bite:', JSON.stringify(await st()));
await page.evaluate(() => window.__game.forcePress(true));
await until(s=>s.topFishY>-0.15,'approach');
await page.screenshot({ path: 'shots/peek-approach.png' });
await until(s=>s.topFishY>0.26,'out');
await page.screenshot({ path: 'shots/peek-out.png' });
const s = await until(s=>s.phase==='mobile','mobile');
await page.evaluate(() => window.__game.forcePress(false));
await frames(12);
await page.screenshot({ path: 'shots/peek-mobile.png' });
console.log('mobile:', JSON.stringify(s));
console.log(logs.join('\n')||'(clean console)');
await b.close();
